from enum import Enum

class Flag(Enum):
    DATE_BEFORE_MIN = "date_before_min"
    DATE_IN_FUTURE = "date_in_future"
    LON_OUT_OF_RANGE = "lon_out_of_range"
    LAT_OUT_OF_RANGE = "lat_out_of_range"
    NO_COORD = "no_coord"
    ZERO_COORD = "zero_coord"
    DEPTH_OUT_OF_RANGE = "depth_out_of_range"
    NO_DEPTH = "no_depth"
    MIN_DEPTH_EXCEEDS_MAX = "min_depth_exceeds_max"
    DEPTH_EXCEEDS_BATH = "depth_exceeds_bath"
    ON_LAND = "on_land"
    NO_MATCH = "no_match"
    NOT_MARINE = "not_marine"
    NO_ACCEPTED_NAME = "no_accepted_name"
    MARINE_UNSURE = "marine_unsure"
    WORMS_ANNOTATION_NO_BIOTA = "worms_annotation_no_biota"
    WORMS_ANNOTATION_UNRESOLVABLE = "worms_annotation_unresolvable"
    WORMS_ANNOTATION_REJECT_HABITAT = "worms_annotation_reject_habitat"
    WORMS_ANNOTATION_REJECT_GROUPING = "worms_annotation_reject_grouping"
    WORMS_ANNOTATION_REJECT_AMBIGUOUS = "worms_annotation_reject_ambiguous"
    WORMS_ANNOTATION_REJECT_FOSSIL = "worms_annotation_reject_fossil"
    WORMS_ANNOTATION_RESOLVABLE_TYPO = "worms_annotation_resolvable_typo"
    WORMS_ANNOTATION_RESOLVABLE_AUTHORITY = "worms_annotation_resolvable_authority"
    WORMS_ANNOTATION_RESOLVABLE_UNPUBLISHED = "worms_annotation_resolvable_unpublished"
    WORMS_ANNOTATION_RESOLVABLE_HUMAN = "worms_annotation_resolvable_human"
    WORMS_ANNOTATION_RESOLVABLE_LOSS = "worms_annotation_resolvable_loss"
    WORMS_ANNOTATION_AWAIT_EDITOR = "worms_annotation_await_editor"
    WORMS_ANNOTATION_AWAIT_PROVIDER = "worms_annotation_await_provider"
    WORMS_ANNOTATION_TODO = "worms_annotation_todo"
